
title: Paint
description: >- # this means to ignore newlines until "baseurl:"
  Painting tools

baseurl: "/mini_games"

theme: # leave it empty

gzip:
  extensions:
    - '.html'
    - '.xml'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME

  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
